name: RestLibrary
version: 0.3.0
author: Rasmus Eneman
description: A simple RestLibrary for quickly setting up a Restserver
dependencies:
  collection: any
  http_server: '>=0.9.2 <0.10.0'
  quiver: '>=0.18.0<0.19.0'
dev_dependencies:
  http: '>=0.10.0 <0.11.0'
  mock: '>=0.10.0+1 <0.11.0'
  unittest: any
